#!/bin/bash
#
#----------------------------------
# single GPU + single CPU example
#----------------------------------
#
#SBATCH --job-name=training4
#SBATCH --output=training4
#
#number of CPUs to be used
#SBATCH --ntasks=1
#
#Define the number of hours the job should run.
#Maximum runtime is limited to 10 days, ie. 240 hours
#SBATCH --time=120:00:00
#
#Define the amount of system RAM used by your job in GigaBytes
#SBATCH --mem=30G
#
#Send emails when a job starts, it is finished or it exits
#SBATCH --mail-user=sbombari@ist.ac.at
#SBATCH --mail-type=END
#
#Pick whether you prefer requeue or not. If you use the --requeue
#option, the requeued job script will start from the beginning,
#potentially overwriting your previous progress, so be careful.
#For some people the --requeue option might be desired if their
#application will continue from the last state.
#Do not requeue the job in the case it fails.
#SBATCH --no-requeue
#
#Define the "gpu" partition for GPU-accelerated jobs
#SBATCH --partition=gpu

#
#Define the number of GPUs used by your job
#SBATCH --gres=gpu:3
#

#
#Do not export the local environment to the compute nodes
#SBATCH --export=NONE
unset SLURM_EXPORT_ENV
#
#
#load an CUDA software module
module load cuda
module load python/3.7.6
module load pytorch
module load torch/devel

#
#print out the list of GPUs before the job is started
srun /usr/bin/nvidia-smi
#
#run your CUDA binary through SLURM's srun
srun python3 main.py
